FROM php:7.4-apache

COPY . /var/www/html

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-enable mysqli \
    && apachectl restart

# RUN docker-php-ext-install mysqli

# RUN docker-php-ext-enable mysqli

# RUN apachectl restart

EXPOSE 80