$install_docker_script = <<SCRIPT
curl -fsSL https://get.docker.com | sudo bash
sudo curl -fsSL "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo usermod -aG docker vagrant
SCRIPT

$master_script = <<SCRIPT
echo Iniciando o Swarm...
sudo docker swarm init --advertise-addr 10.10.10.60:2377
sudo docker swarm join-token --quiet worker > /vagrant/node_token
SCRIPT

$node_script = <<SCRIPT
echo Adicionando máquina como Worker no Swarm...
sudo docker swarm join --token $(cat /vagrant/node_token) 10.10.10.60:2377
SCRIPT

machines = {
  "master" => {"memory" => "1024", "cpu" => "1", "ip" => "60", "image" => "bento/ubuntu-22.04"},
  "node01" => {"memory" => "1024", "cpu" => "1", "ip" => "58", "image" => "bento/ubuntu-22.04"},
  "node02" => {"memory" => "1024", "cpu" => "1", "ip" => "56", "image" => "bento/ubuntu-22.04"},
  "node03" => {"memory" => "1024", "cpu" => "1", "ip" => "55", "image" => "bento/ubuntu-22.04"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "private_network", ip: "10.10.10.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        
      end
      machine.vm.provision "shell", inline: $install_docker_script
      
      if "#{name}" == "master"
        machine.vm.provision "shell", inline: $master_script
      else
        machine.vm.provision "shell", inline: $node_script
      end

    end
  end
end