apiVersion: v1
kind: Pod
metadata:
  name: app-html
  labels:
    app: app-html
spec:
  containers:
  - name: app-html
    image: httpd:2.4.54-bullseye
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    ports:
      - containerPort: 80